### ISSUE TITLE
vault on multiple disks?

### ISSUE THREAD

**Issue by 517qf** [derekp7/snebu#14]
I use snebu for a local backup to a usb drive because I didn't find the combination of features of file-level deduplication (without delta backups) and  compression nowhere else.

My problem is that my backup disk will be full soon. Can I add a second drive at a different location by editing `snebu.conf`?

Can snebu handle backups that are distributed among different folders/drives? How would the restore be affected? I took a quick look at the sqlite database but didn't find anything. So no?

P.S.: Thanks for this great software.

**Comment by derekp7** [comment]
At this time, there is no support for multiple vault locations directly within Snebu.  However, you can do this at the operating system level using Linux LVM (Logical volume management).  Of course the one problem you may have is that you can't convert an existing disk volume over to LVM.  So the way I've addressed this in the past is just setting up an LVM volume on a new disk, copying over all the data from the old one to the new, then wiping the old disk and adding it to the volume group.

If you aren't familiar with using LVM, the command you will need are pvcreate (creates a physical volume), vgcreate (creates a volume group), lvcreate (creates a logical volume), then you can create a filesystem on this logical volume (for example: mkfs -t ext4 /dev/vgname/lvname).  Then when you need to add disks to it, use vgextend to extend the volume group, and lvextend to extend the logical volume, followed by resize2fs to grow the ext4 filesystem (or xfs_growfs if you are using the xfs filesystem).

Let me know if you need more specifics.

**Comment by 517qf** [comment]
Thanks for your quick reply, detailed instructions and offer to help. You assumed correctly that my technical knowledge is very limitied.

I thought about combining disks (either through lvm or a union file system like [mergerFS](https://github.com/trapexit/mergerfs). My concern is disc failure. With mergerfs (and lvm (depending on the lvm configuration)) the data on the surviving disc should be readable but I'm afraid that snebu's restore might not work if a substantial number of the files are missing. My problem is that I can't read C and I don't want to rely on a test restore of a partial dataset. Maybe in this test I'm only lucky because of some special circumstances and I'll only see problems during a real recovery.

I understand that very few people (i.e. no one besides me) is interested in this feature. So thanks again for your time and great software.

I came to snebu because it looks more conservative to me: If I used duplicity or something like attic/borg/duplicati2/restic losing one disc would probably make all of my backup useless because of their deduplication which would scatter most files (that have newer versions) over different disks. And contratry to the popular hardlink-based backups (rsnapshot or many Timemachine clones) your solution doesn't depend on a feature that only works within one filesystem.

P.S.: I don't want to use RAID1. I hope that using an additional disc for an independent backup using a different backup software offers better protection. I hesitate to use the cheaper alternative (RAID5) only for backups because I'm afraid of a user error or misconfiguration on my side that I will only notice during a recovery.

**Comment by derekp7** [comment]
You are correct that if you have a disk failure, you will lose data, as all files are deduplicated based on the sha1 checksum of the file.  So all files that haven't changed between backups, will only have one copy of them.  If the backups are critical (i.e., you rely on them for more than just emergencies), you will want to store them either on a raid 5, or run an rsync from a primary location to a secondary location.
In case your curious, 

There is actually a feature I was looking at adding in, which is the ability to synchronize a backup set from one archive location to another (both metadata stored in the sqlite3 database, and the files themselves).  That way you could, for example, take the current backup from one disk, sync it to a second one, then use the second disk for all subsequent backups.  Or migrate older monthly backups, for example, from one data store to another one, with all files needed by each data store duplicated between them.

But for right now, if you want to get rid of some older data, you can use "snebu expire", and "snebu purge".  You can expire backups by grouping (for example, expire all backups tagged "daily" that are older than 2 weeks, and all "monthly" backups older than 1 year),  If you're current backups aren't tagged based on retention category (for example if they are all showing up as "daily" backups), you can retroactively modify the retention tag using sql commands (update backupsets set retention = 'monthly' where serial = 'xxxxxxxxxx'; ) using sqlite3.  If this is the case, let me know, and I can walk you through the sql commands a bit more.

**Comment by 517qf** [comment]
Thanks again for your detailed answer. After some consideration I think I'll bite the bullet now and buy a multi-disc system for my main snebu backup.
I'll keep the old, nearly full disc as an additional backup layer. I'll take your advice about expire and purge and make some room for future backups. Luckily I don't have to modify my database because I have set the "--retention" option. 
Thanks again for your time and instructional posts!
Cheers!
